spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facebook_clone
    username: postgres
    password: '@Maxton19'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' to automatically sync database schema with entities during development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: INFO  # Change logging level to INFO for production
    org.hibernate.type.descriptor.sql.BasicBinder: WARN  # Reduce verbosity
    org.springframework: INFO
    org.apache: INFO
    org.springframework.security: DEBUG  # Correct indentation

# Optional connection pool configuration (adjust for production)
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.minimum-idle: 5
spring.datasource.hikari.idle-timeout: 30000
spring.datasource.hikari.connection-timeout: 30000
